### ISSUE TITLE
Fix bug in sim1_linear

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1404] opened 2017-03-10 16:52 UTC
`sim1_linear.m` seems to return wrong results. The following mod-file calls different solvers in sequence, using the previous result as the respective starting value.
```
//Endogenous variables
var piV rV yV rrstarV zV Rshock;

//Exogenous variables
varexo epsFG shock epsR;       

//Parameters
parameters alpha beta eta phipi phiy rho sig lambda; // 

//Initialization of parameter values
beta    =0.99;      //Discount factor (=inverse nominal interest rate)
alpha   =0.033;     //sensivity of inflation to output gap, parameter determining marginal cost, 
eta     =1;         //sensivity of inflation to output gap, parameter determining price rigidity
phipi   =1.5;       //parameter determining monetary reaction to inflation
phiy    =0.125;     //parameter determining monetary reaction to output
rho     =0.9;       //AR(1) natural rate
sig     =1;         //intertemporal rate of substitution


lambda=0.25;        // prob. of new info arrival

//model equations
model;

// z Variable
zV = alpha*(yV-yV(-1))+piV;//(pV-pV(-1));

piV= (lambda*alpha/ (1-lambda)) *yV 
+lambda*EXPECTATION(-1)(zV)
+lambda*(1-lambda)*EXPECTATION(-2)(zV)
+lambda*(1-lambda)^2*EXPECTATION(-3)(zV)
+lambda*(1-lambda)^3*EXPECTATION(-4)(zV)
+lambda*(1-lambda)^4*EXPECTATION(-5)(zV)
+lambda*(1-lambda)^5*EXPECTATION(-6)(zV)
+lambda*(1-lambda)^6*EXPECTATION(-7)(zV)
+lambda*(1-lambda)^7*EXPECTATION(-8)(zV)
+lambda*(1-lambda)^8*EXPECTATION(-9)(zV)
;                      //marginal cost is proportional to gap, gap is driver of inflation

//piV=0.99*piV(+1)+0.033*yV;

//IS curve (Output Euler) from Kiley code
yV = yV(+1)-sig*(rV-piV(+1) - rrstarV);

//monetary policy' reaction function
rV = min((1-shock), phipi*(piV(+1) + phiy*yV + epsFG));
//rV = phipi*piV + phiy*yV+Rshock;

Rshock=0.5*Rshock(-1)+epsR;

//Natural real interest rate
rrstarV = rho*rrstarV(-1);
end;

initval;
rV=0;
yV=0;
rrstarV=0;
piV=0;
zV=0;
end;

steady;
check;

shocks;
var shock;
periods 1:15;
values 1;

var epsFG;
periods 16 ;
values -0.0117;
end;

perfect_foresight_setup(periods=30);

perfect_foresight_solver(solve_algo=0); 
nonlinear=oo_.endo_simul;
options_.linear=1;
perfect_foresight_solver(solve_algo=0); 
linear=oo_.endo_simul;
perfect_foresight_solver(solve_algo=0); 
options_.linear=0;
perfect_foresight_solver(solve_algo=0); 
perfect_foresight_solver(solve_algo=4); 
```
But the result of the nonlinear solvers has non-zero residuals in the linear solver and vice versa, while the nonlinear solvers seem to have consistent results.

**Comment by stepan-a** [comment] 2017-03-20 14:35
@JohannesPfeifer Okay. Sorry for not responding sooner to this... The difference you report is obviously expected because the model is non linear . The `sim1` routine is replaced `sim1_linear` if the `linear_approximation` option is used. If the model is non linear we expect a difference, precisely because we only simulate an approximated model. The problem is that the option `linear` triggers `linear_approximation`. I will remove this dependence. Setting automatically `linear_aprroximation` equal to true was not a good idea.

That said we need to fix  the issue with functions non differentiable everywhere.

**Comment by JohannesPfeifer** [comment] 2017-03-20 15:23
@stepan-a I would not remove this. The design for `model(linear)` has always been to use the fastest available algorithm. Of course, over the years we had problems with making sure that the model was truly linear. But this is not a reason to change the solution approach, but to make sure the setup is really linear (which we should be able to do easily)

**Comment by stepan-a** [comment] 2017-03-20 15:33
As you wish... But I am not sure that it is so easy (We need not only to check that these operators are appearing in the model, but also that they operate on endogenous variables. Also it easy to write an inequality constraint that never binds). The fix will wait 4.6.

**Comment by JohannesPfeifer** [comment] 2017-03-20 15:37
@stepan-a I wouldn't overthink it. If you want to use these operators, do not say your model is linear. I wouldn't go so far to check whether constraints bind.

**Comment by houtanb** [comment] 2017-04-04 10:25
@stepan-a is it ok with you if I implement the check that @JohannesPfeifer proposes? I would change the warning message to be: `warnings << "WARNING: you are using a function (max, min, abs, sign) or an operator (<, >, <=, >=, ==, !=) in a model declared 'linear' which may be unsuitable in a stochastic context; see the reference manual, section about \"Expressions\", for more details." << endl;` since, as you mention, the use of these operators does not necessarily imply a nonlinear model. The `if` statement would also check that the model was declared `linear`. @JohannesPfeifer do you agree with the modified message and condition (I'm guessing you overlooked the specification of `linear` in the check)

**Comment by JohannesPfeifer** [comment] 2017-04-04 11:55
@houtanb The present problem does not arise in a stochastic context, but in perfect foresight. As far as I can see, no warning is triggered in this case. The proposal was to issue a warning like the above one if one declares `linear` with any nonlinear operator regardless of context.

**Comment by houtanb** [comment] 2017-04-04 14:15
@JohannesPfeifer I agree. I had misread your comment above. I thought that was the check you were proposing. I had not seen that you said "a check similar to..."

**Comment by houtanb** [comment] 2017-04-04 14:18
How's this for a proposed warning: `"WARNING: you have declared your model 'linear' but you are using a function (max, min, abs, sign) or an operator (<, >, <=, >=, ==, !=) which potentially makes it non-linear.` Please suggest modifications to the warning message and, if @stepan-a agrees, I'll make the change.

**Comment by JohannesPfeifer** [comment] 2017-04-04 21:28
@houtanb The message is perfect for me. @stepan-a What do you think?

**Comment by stepan-a** [comment] 2017-04-04 21:39
@houtanb please apply the patch, it's fine with me.

**Comment by houtanb** [comment] 2017-04-05 09:13
A more complete will be made in 4.6 following @stepan-a 's [earlier comment](https://github.com/DynareTeam/dynare/issues/1404#issuecomment-287796888)

**Comment by stepan-a** [comment] 2017-10-10 10:13
@houtanb I close this issue because the original problem is fixed. Can you please open another issue for 4.6.

**Closed by stepan-a** 2017-10-10 10:13 UTC
Labels: bug, preprocessor
