### ISSUE TITLE
external functions and third order perturbation

### ISSUE THREAD

**Issue by stepan-a** [DynareTeam/dynare#1229] opened 2016-06-14 12:17 UTC
It appears that we did not implement the possibility to use external functions when solving DSGE models at third order. I thought that when the derivates are not provided by the user, Dynare computed the derivates numerically. It seems that this mechanism is not triggered at third order. Is this intentional?

**Comment by JohannesPfeifer** [comment] 2016-06-14 12:18
@stepan-a No, this is not intentional. This ticket is a duplicate of #300

**Closed** 2016-06-14 12:21 UTC
Labels: bug, decision, discussion, duplicate
