### ISSUE TITLE
Adjust apt-get build-dep

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1263] opened 2016-08-07 16:08 UTC
Currently, the `texlive-fonts-extra` package containing `ccicons` for building the documentation is missing. The `README.md` must also be adjusted accordingly.

**Comment by stepan-a** [comment] 2016-08-23 19:56
Only @sebastien-villemot can do that... I have the impression that this dependency is only pertinent for the master branch. So this will have to wait the release of the next stable.

**Comment by MichelJuillard** [comment] 2016-08-24 08:14
@JohannesPfeifer 
```
the texlive-fonts-extra package containing ccicons for building the documentation is missing.
```
from which file?

**Comment by JohannesPfeifer** [comment] 2016-08-24 08:20
@MichelJuillard We say you should run `apt-get build-dep dynare`
to automatically install all Linux packages required to build Dynare. But this is not true, because the documentation uses the `ccicons` LaTeX package, which is contained in the `texlive-fonts-extra` Linux package. But the `texlive-fonts-extra` package is not listed as a package required to build Dynare and is therefore not installed when you run `apt-get build-dep dynare`

**Comment by MichelJuillard** [comment] 2016-08-24 08:23
@JohannesPfeifer, you need to report a bug for the dynare package in Debian.

**Comment by stepan-a** [comment] 2016-08-24 08:36
@MichelJuillard It's not a bug if the package is not needed for the stable version of Dynare...

**Comment by sebastien-villemot** [comment] 2016-08-24 08:47
Indeed, Debian (and Ubuntu) still have the stable version of Dynare, which does not require `texlive-fonts-extra`, so there is no bug to be reported there.
The problem will be fixed when a new Dynare release is made (in which case I will update the dependencies).

**Comment by sebastien-villemot** [comment] 2016-08-24 08:48
In the meantime I guess the solution is adjust the wiki to tell people to `apt install texlive-fonts-extra` if they are using the `master` branch.

**Closed** 2016-08-24 12:49 UTC
