### ISSUE TITLE
When using gnuplot on octave, most graphs titles are cut

### ISSUE THREAD

**Issue by felipeboralli** [DynareTeam/dynare#1300] opened 2016-10-05 17:10 UTC
When using gnuplot on octave, most graphs titles are cut a bit.
It seems the titles are shifted upwards, because when there is a second row of graphs in the window, their titles seem to invade the upper row.

![2](https://cloud.githubusercontent.com/assets/22381123/19123477/32dd3916-8b05-11e6-8af1-172438cf9051.png)
![3](https://cloud.githubusercontent.com/assets/22381123/19123478/32de3348-8b05-11e6-958c-8d22213691d4.png)
![4](https://cloud.githubusercontent.com/assets/22381123/19123479/32e291ea-8b05-11e6-8edf-01b68f995c46.png)

**Comment by JohannesPfeifer** [comment] 2016-10-06 20:16
@felipeboralli This seems to be an Octave bug. With `Octave 4.0.3` (which we do not yet fully support), I cannot reproduce the problem. Which version and OS are you using?

**Comment by houtanb** [comment] 2016-10-14 10:33
I checked in 4.2.0-rc2 and the problem does not exist there either so I am closing this ticket

**Closed by houtanb** 2016-10-14 10:33 UTC
Labels: octave
