### ISSUE TITLE
Expand model_diagnostics to test whether the model is truly linear

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#419] opened 2013-06-04 07:53 UTC
Often users specify model(linear), but don't enter all FOCs correctly. Testing in model_diagnostics whether all equations are linear and displaying the wrong equations would provide a valuable diagnostic tool. Alternatively, the preprocessor could check whether the Hessian g2 is a zero matrix if the linear option is specified.

**Comment by JohannesPfeifer** [comment] 2015-10-14 09:03
@houtanb Is there an easy way to do this in the preprocessor? If not, we should just make sure that when we encounter a ```model_diagnostic``` statement in a mod-file, we actually compute g2 (i.e. we always use at least order=2 for generating the derivatives)

**Comment by MichelJuillard** [comment] 2015-10-14 09:08
Checking g2 is much easier. However, we need trigger the computaton of second derivatives in the preprocessor when model_diagnostic is present in the *.mod file

**Comment by houtanb** [comment] 2015-10-14 09:31
@JohannesPfeifer can you post a .mod file that should fail.

**Comment by JohannesPfeifer** [comment] 2015-10-14 09:34
```
var y, c, k, a, h, b;
varexo e, u;

parameters beta, rho, alpha, delta, theta, psi, tau;

alpha = 0.36;
rho   = 0.95;
tau   = 0.025;
beta  = 0.99;
delta = 0.025;
psi   = 0;
theta = 2.95;

phi   = 0.1;

model(linear);
c*theta*h^(1+psi)=(1-alpha)*y;
k = beta*(((exp(b)*c)/(exp(b(+1))*c(+1)))
    *(exp(b(+1))*alpha*y(+1)+(1-delta)*k));
y = exp(a)*(k(-1)^alpha)*(h^(1-alpha));
k = exp(b)*(y-c)+(1-delta)*k(-1);
a = rho*a(-1)+tau*b(-1) + e;
b = tau*a(-1)+rho*b(-1) + u;
end;

initval;
y = 1;
c = 0.80359242014163;
h = 0.29175631001732;
k = 11.08360443260358;
a = 0;
b = 0;
e = 0;
u = 0;
end;

shocks;
var e; stderr 0.009;
var u; stderr 0.009;
var e, u = phi*0.009*0.009;
end;

stoch_simul;
```

**Comment by houtanb** [comment] 2015-10-14 09:36
Hmmm, the previous comments have not been clear then. Should this check be triggered when the model is declared as linear or when it is linear and ```model_diagnostics``` has been passed?

**Comment by JohannesPfeifer** [comment] 2015-10-14 09:39
The check should be triggered when the user declares the model is linear. We want to find out where the nonlinearity is. I envision this to be a feature of ```model_diagnostics```, because generally checking for actual linearity seems like an overkill that robs the efficiency of declaring a model as linear

**Comment by houtanb** [comment] 2016-07-22 18:39
@JohannesPfeifer can you also provide a .mod file where the model is declared linear but has been correctly specified and thus should pass the test?

**Comment by JohannesPfeifer** [comment] 2016-07-23 06:33
You can use https://github.com/DynareTeam/dynare/blob/master/tests/ls2003/ls2003.mod

**Comment by JohannesPfeifer** [comment] 2016-07-26 08:38
@houtanb I feel that the current check is too strong. The preprocessor just stops without providing any useful debugging information. Is there a way to display the affected equation(s)? Or could we turn this into a warning instead of an error so that execution continues and one can e.g. try `resid`, which often helps.

**Comment by houtanb** [comment] 2016-07-27 17:48
@JohannesPfeifer you want the preprocessor to print the equations or the equation numbers?

**Comment by JohannesPfeifer** [comment] 2016-07-27 17:57
Ideally, the equation tag and, if not specified, the equation number. If easy to do, displaying the actual equation would be great, because counting equations in big models can be cumbersome.

**Comment by houtanb** [comment] 2016-07-27 18:52
@JohannesPfeifer it's easy to print the equations with parameter/variable arrays as displayed in the `_static` and `_dynamic` files. Is this still useful or should I stick with the equation number/tags?

**Comment by JohannesPfeifer** [comment] 2016-07-29 06:12
@houtanb I think this is fine for now.

**Comment by JohannesPfeifer** [comment] 2016-08-01 07:35
@houtanb Hi could you please add an additional check that `linear` cannot be used with Ramsey. Otherwise, a cryptic message on nonlinear equations actually relating to the auxiliary equations will appear.

**Comment by MichelJuillard** [comment] 2016-08-01 12:26
This is a bug that should be fixed. @JohannesPfeifer can you please provide an example?

**Comment by JohannesPfeifer** [comment] 2016-08-01 12:29
Here it is:
```
var r_m r_hat c_hat v_hat m_hat y_hat pi_hat w_hat z_hat a_hat mu_hat g_hat 
    R_hat;

% Exogenous variables:
varexo epsilon e_a e_g e_mu e_v e_z e_rm ;
 
% Parameters:
parameters eta_R R_ss eta_h eta_c s_c kappa phi sigma_r_m sigma_m sigma_a
           sigma_g sigma_mu sigma_v sigma_z rho_a rho_g rho_mu rho_v rho_z 
           beta omega sigma_tilda rho_pi eta_ch sigma_c sigma_h eta_hc 
           alpha lambda_x lambda_R v_p;

%**************************************************************************

%INITIALISATION 

v_p = 6;
beta = 0.99; 
s_c = 0.8;
sigma_tilda = 1;
omega = 3.5;
R_ss = 1.0146; 
eta_ch = 0.3; 
sigma_h = 3.5; 
eta_hc = 2.8;
alpha = 0.3304;
sigma_c = 0.8;
rho_pi = 0.85;
rho_a = 0.5;
rho_g = 0.5;
rho_mu = 0.5;
rho_v = 0.5;
rho_z = 0.5;

eta_h = 0.0284;
eta_c = 0.2649;

sigma_a = 1;
sigma_g = 1; 
sigma_mu = 1; 
sigma_v = 1; 
sigma_z = 1;
sigma_m = 1; 
sigma_r_m = 1;

phi = 0.5;
kappa = ((1-alpha)*(1-alpha*beta))/alpha;
eta_R = R_ss/(sigma_h*(R_ss-1));

lambda_x = ((1-alpha)*(1-alpha*beta))/(sigma_tilda+omega);
lambda_R = (eta_R*lambda_x/(sigma_tilda+omega))*(1/v_p);

%**************************************************************************
%**************************************************************************

% The Model:
model(linear);

    a_hat = rho_a*a_hat(-1) + e_a;
    g_hat = rho_g*g_hat(-1) + e_g;
    mu_hat = rho_mu*mu_hat(-1) + e_mu;
    v_hat = rho_v*v_hat(-1) + e_v;
    z_hat = rho_z*z_hat(-1) + e_z;
    log(r_m) = e_rm;
    
    r_hat = R_hat-pi_hat(+1);
    
    c_hat(+1) = (v_hat(+1)+(eta_ch*(m_hat-pi_hat(+1)+z_hat(+1)))+
        sigma_tilda*c_hat-v_hat-eta_ch*(m_hat(-1)-pi_hat+z_hat)+
        R_hat-pi_hat(+1))*sigma_tilda;
    
    w_hat = omega*(y_hat-a_hat)-v_hat+sigma_tilda*c_hat-eta_ch*(m_hat(-1)-
        pi_hat+z_hat)+mu_hat;
    
    pi_hat = beta*pi_hat(+1)+kappa*(w_hat-a_hat);
    
    y_hat = (0.8+eta_c)*c_hat+g_hat-eta_h*(m_hat(-1)-pi_hat+z_hat); 
        %1-(g/y)-(phi/y)=0.8
    
    m_hat = -eta_R*R_hat+(eta_hc/sigma_h)*c_hat(+1)+pi_hat(+1)+
        ((1-sigma_h)/sigma_h)*z_hat(+1);
    
    %R_hat = rho_pi*pi_hat+epsilon; %(^m)
    
end; 

%**************************************************************************
 
shocks;
var e_a = sigma_a^2;
var e_g = sigma_g^2;
var e_mu = sigma_mu^2;
var e_v = sigma_v^2;
var e_z = sigma_z^2;
var e_rm = sigma_r_m^2;
var epsilon = sigma_m^2;
end;

%**************************************************************************

initval;
a_hat = 0.5;
g_hat = 0.5;
mu_hat = 0.5;
v_hat = 0.5;
z_hat = 0.5;
r_m = 0.5;
end;

%**************************************************************************

planner_objective pi_hat^2 + lambda_x*y_hat^2 + lambda_R*R_hat^2; 

ramsey_policy(planner_discount=0.999);

stoch_simul c_hat y_hat pi_hat m_hat R_hat r_hat;
```

**Comment by houtanb** [comment] 2016-08-11 13:48
@MichelJuillard are you going to do something other throw an error when ```(mod_file_struct.ramsey_model_present || mod_file_struct.ramsey_policy_present) && linear)``` holds in ```ModFile::checkPass()```? If not, I can push this right now....

**Comment by MichelJuillard** [comment] 2016-08-11 14:06
@houtanb: we need to understand what the problem is. A linear model shouldn't break Ramsey

**Comment by JohannesPfeifer** [comment] 2016-08-11 14:24
The issue is straightforward. If the model is linear, the Ramsey equations will have a product of multiplier and the linear equation, which itself is now nonlinear and will trigger the error. The cleanest way would be to only check linearity of the original equations.

**Comment by MichelJuillard** [comment] 2016-08-11 14:28
Thanks @JohannesPfeifer , that is what needs to be done. It would be weird and confusing to throw an error in this case

**Comment by JohannesPfeifer** [comment] 2016-11-29 10:13
@stepan-a I think some solution must be part of 4.5. It is not about the enhancement as the label suggests, but rather about the fact that the implemented change introduces a bug that prevents using the Ramsey command with the `linear` option (see the attached mod-file). If we cannot do what @MichelJuillard suggested in his last post, we should at least transform the error into a warning so that preprocessing continues.

**Closed** 2016-11-29 13:37 UTC
Labels: enhancement
